builders:
  migration_info:
    import: "package:angel_migration_runner/builders.dart"
    builder_factories:
      - migrationInfoBuilder
    build_extensions:
      .dart:
        - .migration_info.json
    required_inputs:
      - .dart
    auto_apply: all_packages
    applies_builders:
      - angel_serialize_generator|angel_serialize
      - angel_orm_generator|angel_orm