name: angel_migration_runner
version: 1.0.0-alpha
description: Database migration runner for Angel's ORM.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/migration
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_migration: ^1.0.0-alpha
  args: ">=0.13.4 <2.0.0"
  postgres: ^0.9.5